### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by healer963** [BIMSBbioinfo/scmaui-experiments#1]
Why is the sample data set in the tutorial three cell types, and the data set given is not three, but many?
![1](https://github.com/user-attachments/assets/e6be10a2-6ffa-4491-b397-b2a611a62c78)

**Comment by hanyangii** [comment]
Hello, thank you very much for your interest!

Yes, the dataset has a full set of cell types from bone marrow. We used only a subset of the dataset for simple examples.

**Comment by healer963** [comment]
Ok, thank you very much

**Comment by healer963** [comment]
The GSE194122 dataset shows that there are 10 donors, and you selected 8, right? Could you please provide the complete data set？
